module2-task1
htmlacademy-ecmascript/1861971-cinemaddict-17 pull request #5
Opened 2022-05-03 18:02 UTC by GaryTe

2022-05-05 17:28 UTC, DmitryMarkov requested changes
Замечания из прошлого PR не исправлены, хотя я просил об этом: https://github.com/htmlacademy-ecmascript/1861971-cinemaddict-17/pull/4

2022-05-05 17:28 UTC, DmitryMarkov commented on src/presenter/drawing-markup-elements-presenter.js
> +    this.generatorObject = generatorObject;
зачем эти присваивания?

2022-05-05 17:28 UTC, DmitryMarkov commented on src/model/generator-object.js
> +  getObject = () => this.generator;
функция названа неверно. из названия выходит, что она возвращает объект, а она возвращает массив объектов

2022-05-05 17:28 UTC, DmitryMarkov commented on src/presenter/drawing-markup-elements-presenter.js
> +    for(let i=0; i<this.containerForObject.length; i++){
можно весь цикл заменить методом массива `map`

2022-05-05 17:28 UTC, DmitryMarkov commented on src/presenter/drawing-markup-elements-presenter.js
> +    this.containerForObject = [...this.generatorObject.getObject()];
контейнер для объектов называется массив, лучше называть вещи именами привычными для программистов, добавляя в конце List или `s` к сущности. Object - слишком абстрактно. Ты же знаешь, что конкретно там внутри? Именование - крайне важная часть успеха в программировании, надо больше внимания этому уделить

2022-05-05 17:28 UTC, DmitryMarkov commented on src/temporary-data.js
> +  'id': '42',
id у объектов должен быть разным

2022-05-05 17:28 UTC, DmitryMarkov commented on src/utils.js
> +  if(data === true){
можно сократить до:
```suggestion
  if(data){
```

2022-05-05 17:28 UTC, DmitryMarkov commented on src/view/popup-view.js
> +*/
комменты запрещены

2022-05-05 17:28 UTC, DmitryMarkov commented on src/view/popup-view.js
>            <li class="film-details__comment">
комменты тоже надо брать из рыбы

2022-05-16 07:58 UTC, maks88sgt approved these changes

2022-05-16 07:58 UTC, maks88sgt commented on Readme.md
> +* Наставник: `Максим Дробышев`.
Вставь пожалуйста здесь ссылку на профиль, чтобы это работало также как и с твоим профилем

2022-05-16 08:01 UTC, merged